image: golang:1.11.6-alpine3.8

stages:
- test
- deploy

format-test:
  stage: test
  script:
  - export CGO_ENABLED=0
  - go fmt
  - go vet
  - go test -cover

deploy:
  image: google/cloud-sdk:241.0.0
  stage: deploy
  script:
  - gcloud app deploy --no-promote
  when: manual
