image: golang:1.8.6-alpine3.6

stages:
- test
- deploy

format-test:
  stage: test
  script:
  - go fmt
  - go vet
  - go test

deploy:
  image: google/cloud-sdk:183.0.0
  stage: deploy
  script:
  - gcloud app deploy --no-promote
  when: manual
